create table books
(
    id        int4 generated by default as identity,
    name      varchar(255) not null,
    price     float4 not null,
    num       int4,
    warehouse varchar(255) not null,
    primary key (id)
);

create table customer
(
    id       int4 generated by default as identity,
    discount int4,
    area     varchar(255) not null,
    surname  varchar(255) not null,
    primary key (id)
);

create table buy
(
    order_number    int4 generated by default as identity,
    sum             float4 not null,
    date_buy        timestamp not null,
    num             int4 not null,
    book_id         int4 not null,
    customer_id     int4 not null,
    store_id        int4 not null,
    primary key (order_number)
);

create table store
(
    id          int4 generated by default as identity,
    commission  int4,
    area        varchar(255) not null,
    name        varchar(255) not null,
    primary key (id)
);

alter table if exists buy
    add constraint buy_book_fk
    foreign key (book_id) references books;

alter table if exists buy
    add constraint buy_customer_fk
    foreign key (customer_id) references customer;

alter table if exists buy
    add constraint buy_store_fk
    foreign key (store_id) references store;